version: '3.7'

services:
  web:
    build: .
    container_name: internal_service_platform
    command: bash -c "python /usr/src/app/manage.py migrate --noinput &&
              python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    #    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: