version: "3.3"

services:
  web:
    build: .
    container_name: internal_service_platform
    command: bash -c "./manage.py collectstatic --noinput && 
             ./manage.py migrate  && 
              gunicorn -b 0.0.0.0:8001 internal_service_platform.wsgi:application"
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - ./media:/usr/src/app/media
    networks:
      - internal_platform_network

  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - internal_platform_network

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - internal_platform_network

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_container
    restart: always
    image: nginx_image
    volumes:
      - static_volume:/usr/src/app/static
      - ./media:/usr/src/app/media
      - ./docker/nginx/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/www:/var/www/certbot
    networks:
      - internal_platform_network

    depends_on:
      - web
    ports:
      - "81:80"

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    restart: always
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot -d fregi.pp.ua --agree-tos --email admin@fregi.pp.ua --non-interactive --renew-by-default; sleep 12h & wait $${!}; done;'
    volumes:
      - ./docker/nginx/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/log:/var/log/letsencrypt
      - ./docker/nginx/www:/var/www/certbot
    networks:
      - internal_platform_network

networks:
  internal_platform_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.120/24

volumes:
  pg_data:
  static_volume:
  media_volume:
