version: '3.7'

services:
  web:
    build: .
    container_name: internal_service_platform
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  pg_data: